### ISSUE TITLE
Input data format and comparing betn experimental groups

### ISSUE THREAD

**Issue by guray003** [andymckenzie/BRETIGEA#11]
Hi Andy.

I'm going through your tutorial to use BRETIGEA to deconvolute cell type populations from mouse brain seq data from two different experimental groups similar to the Fig 3A in this [paper](https://www.sciencedirect.com/science/article/pii/S000632232101369X). 

Apologies, I'm still a new to using this tool but I'm not entirely clear on the format of the input seq data. Do we use raw counts or norm counts? And what does it mean when you have negative values as you do in the proportion analysis table on page 6 of your manual? Lastly, is there a way to directly compare cell type proportions directly between the two groups within the BRETIGEA framework?

Thanks,

Anand

**Comment by andymckenzie** [comment]
Hi Anand, 

Hello and thanks for using BRETIGEA. 

> Do we use raw counts or norm counts? 

The package is flexible on the data input format. The gene expression input format used in the example data set from the Allen Brain Atlas was normalized RPKM values, which was adjusted for RNA integrity number (RIN) and batch.

> And what does it mean when you have negative values as you do in the proportion analysis table on page 6 of your manual? 

The proportions can be negative for the same reason that they are negative in CellCODE, from which we adapted the singular value decomposition method. For more on this including how to interpret the variables, you can review the paper describing CellCODE https://academic.oup.com/bioinformatics/article/31/10/1584/177237, where they note: "We emphasize that because they are eigenvectors of an SVD, SPVs do not directly quantify cell-type proportions; in particular, SPVs will take on negative values. Nevertheless, SPV values should reflect the relative differences in cell-type composition. As such, SPVs should be well-correlated with true cell-type composition."

> Lastly, is there a way to directly compare cell type proportions directly between the two groups within the BRETIGEA framework?

There are a variety of ways you could compare the cell type proportions between groups. A standard method for comparing the cell type proportions between two groups might be something like a t-test. 

Hope this helps. 

Andy
