### ISSUE TITLE
Negative estimations in BRETIGEA

### ISSUE THREAD

**Issue by mmaiensc** [andymckenzie/BRETIGEA#13]
Hi,

I am running BRETIGEA on a couple RNA-seq data sets, and I’ve noticed that the brainCells() function often returns negative value for the estimates. This can also be observed in the vignette for the R package. What is the appropriate interpretation in this case?

Relatedly, what is the scale of the values returned by this function? The manual would indicate that it is an estimated proportion, though the numbers do not come close to summing to 1 (even if resetting negative values to 0).

Thanks,
Mark

———
Mark Maienschein-Cline, PhD
Director, Research Informatics Core
Research Resources Center
University of Illinois at Chicago

**Comment by andymckenzie** [comment]
Hi Mark, 

Thanks for this question and for using BRETIGEA! 

I think the [answer to Issue #2](https://github.com/andymckenzie/BRETIGEA/issues/2
) might answer your question. I'm pasting part of it below. Please feel free to re-open the issue or ask another question if this doesn't answer what you were asking! 

"The proportions are negative for the same reason that they are negative in CellCODE, from which we adapted the singular value decomposition method. For more on this including how to interpret the variables, you can review the paper describing CellCODE https://academic.oup.com/bioinformatics/article/31/10/1584/177237, where they note: "We emphasize that because they are eigenvectors of an SVD, SPVs do not directly quantify cell-type proportions; in particular, SPVs will take on negative values. Nevertheless, SPV values should reflect the relative differences in cell-type composition. As such, SPVs should be well-correlated with true cell-type composition.""

**Comment by mmaiensc** [comment]
Great, thanks!
