### ISSUE TITLE
Results interpretation

### ISSUE THREAD

**Issue by talponer** [andymckenzie/BRETIGEA#2]
Dear developer,

I have a bulk RNA-seq data set that I would like to analyze using BRETIGEA. The steps to produce the results are very simple, but I have difficulties understanding the output. In the vignette section 4 ('Relative cell type proportion estimation') you run the brainCell function to obtain the 'surrogate proportion variables' for each sample and each cell type. How to interpret them? Why are some proportion negative? Are results for different samples (rows in the vignette table) comparable?

Thank you very much for clarifying this points
regards
r

**Comment by andymckenzie** [comment]
Hello and thank you for using BRETIGEA!

>  the vignette section 4 ('Relative cell type proportion estimation') you run the brainCell function to obtain the 'surrogate proportion variables' for each sample and each cell type. How to interpret them? Why are some proportion negative? 

The proportions are negative for the same reason that they are negative in CellCODE, from which we adapted the singular value decomposition method. For more on this including how to interpret the variables, you can review the paper describing CellCODE https://academic.oup.com/bioinformatics/article/31/10/1584/177237, where they note: "We emphasize that because they are eigenvectors of an SVD, SPVs do not directly quantify cell-type proportions; in particular, SPVs will take on negative values. Nevertheless, SPV values should reflect the relative differences in cell-type composition. As such, SPVs should be well-correlated with true cell-type composition."

> Are results for different samples (rows in the vignette table) comparable?

Yes, this is the purpose of calculating the surrogate proportion variables: so that they can be compared on a relative basis across samples. This is how we describe it in our manuscript, https://www.nature.com/articles/s41598-018-27293-5: "After estimation from bulk brain gene expression samples, the surrogate cell type proportion variables can be used to find the correlation of cell type changes with matched phenotype data, for example to uncover cell type proportion changes in disease states. The cell type proportions can also be used as a covariate for adjusting away the effect of brain cell type proportions on the expression of individual genes, which can be followed by downstream applications such as differential expression and/or differential correlation analysis." 

Hope this helps.

**Comment by talponer** [comment]
Thanks, that was helpful!
