### ISSUE TITLE
adding immune cell types to existing brain cell types marker gene df

### ISSUE THREAD

**Issue by kgaonkar6** [andymckenzie/BRETIGEA#3]
Hi,

I would like to use this tool to identify relative cell-proportions of cell types in brain and immune cell types. Specifically interested in monocytes so I tried to add ~300 marker genes for monocyte from literature review and xCell and run findCells function on all samples with marker_gene_df=the existing 6000 marker genes for brain cells provided + ~300 marker gene for monocyte.

I do get some interesting results so I was wondering if this is a valid use of the findCells function to look for relative cell proportions of additional cell types along with brain cells?

Thank you,
Krutika

**Comment by andymckenzie** [comment]
Hi Krutika, 

Thank you for using BRETIGEA and for the interesting question. 

I'm not sure how the list of monocyte markers would interact with the list of markers for the other brain cell types. For example, I'm not sure how it would interact with the microglia marker list. If they were independent, then your use of findCells() with those markers might be valid. 

However, it really depends on several of the specifics of your application and the goals of your analysis, so it's hard to give a general answer with much certainty. I'm sorry I can't give you a more precise answer.

**Comment by kgaonkar6** [comment]
Thank you for your prompt reply!

The general required application of the analysis would be to identify relative surrogate proportions variables of microglia vs monocytes in brain samples. Would the above methods seem valid for this?

**Comment by andymckenzie** [comment]
The main consideration for generating SVPs for microglia vs monocytes in brain samples is whether you can find specific gene markers for each of those brain cell types. The original BRETIGEA data set does not distinguish between these two cell types but I expect that this would be possible to generate from elsewhere.

Since this would be a novel application, I think that it would be best to either find a control data set where you can validate your method or specify that your analysis is preliminary/hypothesis-generating.

**Comment by kgaonkar6** [comment]
Makes sense, as you mentioned I'll add that the results from the analysis would be preliminary until  further validation is performed.

Thanks!

**Comment by andymckenzie** [comment]
Hi kgaonkar6, 

I hope that your issue has been solved. I'm going to close this issue for now. Please feel free to re-open another one if you have additional problems.
