### ISSUE TITLE
Question about gene expression quantization method

### ISSUE THREAD

**Issue by rgalvin516** [andymckenzie/BRETIGEA#7]
Hello,

Thanks a lot for compiling this resource. I am wondering if the method of gene quantization in my expression matrix will have an impact on the results of the brainCells function. I read your supplementary methods and saw that you obtained raw RNA-seq data, aligned it, and normalized gene counts using a quantile approach. My data is available as RSEM expected counts, TPM, and FPKM but I do not have access to raw data. Would a matrix based on FPKM gene quantization, for example, be valid with this pipeline?

Thank you for your time

**Comment by andymckenzie** [comment]
Hello rgalvin516, 

Thank you for using BRETIGEA and I'm sorry for the delayed response. 

The method of transformation of the gene expression matrix will have an effect on the results of the brainCells function because it is essentially a wrapper for principal components analysis or singular value decomposition. How one should transform gene expression data prior to using PCA/SVD is somewhat of a controversial one within the bioinformatics field. You can find all sorts of discussions on this topic online, for example, https://www.biostars.org/p/172985/. 

Personally, my opinion is that many different approaches could be useful depending upon the goals of your particular experiment. If possible, it would be ideal to identify a metric of external validity with whatever method you are choosing. 

I hope this helps and sorry I don't have a more straightforward answer.
